name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Deploy to server
        run: |
          sudo apt install sshpass
          sshpass -p ${{ secrets.SSH_PASSWORD}} ssh christian@144.126.152.251 <<'ENDSSH'
          cd ${{ secrets.WORK_DIR }}
          ls -l
          git pull
          docker compose down 
          docker compose build
          docker compose up
          ENDSSH
