name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -  shell: bash
         env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
            SSH_USER: ${{ secrets.SSH_USER }}
            WORK_DIR: ${{ secrets.WORK_DIR}}
            MAIN_BRANCH: ${{ secrets.MAIN_BRANCH}}
            
      - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
        run: |
          echo $SSH_PRIVATE_KEY 
          ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh $SSH_USER@$SSH_HOST "cd $WORK_DIR && git checkout $MAIN_BRANCH && git pull && exit"
      - name: re-deploy on server
        run: docker compose down && docker compose build && docker compose up
